/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tikTakToe;



public class App {
    
    public static void main(String[] args) {
        
        Game.playing();

    }
}
