/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package magicSquare;


public class App {

    public static void main(String[] args) {
        
        Methods.cuby();
    }
}
